name: FE CI on ECR

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      bump_minor:
        description: "버전 증가(true=minor+1, false=patch+1)"
        required: false
        type: boolean
        default: false

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  # ECR 리포지토리 이름(예: project-hybrid-frontend)
  ECR_REPO: ${{ secrets.ECR_REPO }}
  IMAGE_TAG: ${{ github.sha }}

  # overlay 리포(owner 자동 계산) — 필요한 경우 시크릿을 우선 사용
  ENV_OVERLAY_REPO: ${{ secrets.ENV_OVERLAY_REPO || format('{0}/project-hybrid_frontend_gitops', github.repository_owner) }}
  DEV_OVERLAY_PATH: ${{ secrets.DEV_OVERLAY_PATH || 'environments/dev/frontend/kustomization.yaml' }}

  # ECR 생성 시도 (권한 없으면 false 권장)
  ALLOW_CREATE_ECR: "false"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout app
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Assert STS
        run: aws sts get-caller-identity

      - name: Login to Amazon ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Guard variables
        run: |
          set -eu
          : "${ECR_REPO:?ECR_REPO empty}"
          : "${IMAGE_TAG:?IMAGE_TAG empty}"
          echo "REGISTRY=${{ steps.ecr.outputs.registry }}"
          echo "ENV_OVERLAY_REPO=${ENV_OVERLAY_REPO}"
          echo "DEV_OVERLAY_PATH=${DEV_OVERLAY_PATH}"

      # vX.Y.Z 자동 산정 (옵션)
      - name: Resolve version tag (vX.Y.Z)
        id: ver
        env:
          DEFAULT_MAJOR: "1"
        shell: bash
        run: |
          set -euo pipefail
          BUMP="${{ github.event.inputs.bump_minor }}"
          BUMP="$(echo "${BUMP:-false}" | tr '[:upper:]' '[:lower:]')"
          EXISTING=$(
            aws ecr describe-images \
              --repository-name "${ECR_REPO}" \
              --query "imageDetails[].imageTags[]" \
              --output text 2>/dev/null | tr '\t' '\n' | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' || true
          )
          MAJOR="${DEFAULT_MAJOR}"
          if [ -n "${EXISTING}" ]; then
            CUR_MINOR_MAX=$(printf '%s\n' ${EXISTING} \
              | awk -F'[v\\.]' -v maj="${MAJOR}" '$2==maj {print $3}' \
              | sort -n | tail -n1)
            CUR_MINOR_MAX="${CUR_MINOR_MAX:-0}"
          else
            CUR_MINOR_MAX="0"
          fi
          if [ "${BUMP}" = "true" ]; then
            MINOR=$(( CUR_MINOR_MAX + 1 )); PATCH=0
          else
            MINOR="${CUR_MINOR_MAX}"
            if [ -n "${EXISTING}" ]; then
              PATCH_MAX=$(printf '%s\n' ${EXISTING} \
                | awk -F'[v\\.]' -v maj="${MAJOR}" -v min="${MINOR}" '$2==maj && $3==min {print $4}' \
                | sort -n | tail -n1)
              PATCH=$([ -z "${PATCH_MAX:-}" ] && echo 0 || echo $((PATCH_MAX + 1)))
            else
              PATCH=0
            fi
          fi
          VERSION_TAG="v${MAJOR}.${MINOR}.${PATCH}"
          echo "version=${VERSION_TAG}" >> "$GITHUB_OUTPUT"
          echo "::notice:: VERSION_TAG=${VERSION_TAG}"

      - name: Build image
        run: docker build -t $ECR_REPO:$IMAGE_TAG .

      - name: Ensure ECR repo exists (describe or create)
        env:
          REGISTRY: ${{ steps.ecr.outputs.registry }}
        run: |
          set -euo pipefail
          if aws ecr describe-repositories --repository-names "$ECR_REPO" --region "$AWS_REGION" >/dev/null 2>&1; then
            echo "ECR repo found: $ECR_REPO"
          elif [ "$ALLOW_CREATE_ECR" = "true" ]; then
            echo "Creating ECR repo: $ECR_REPO"
            aws ecr create-repository --repository-name "$ECR_REPO" --region "$AWS_REGION" >/dev/null
          else
            echo "ECR repo '$ECR_REPO' not found. Create it once or set ALLOW_CREATE_ECR=true."
            exit 1
          fi

      - name: Tag image for ECR
        env:
          REGISTRY: ${{ steps.ecr.outputs.registry }}
        run: |
          docker tag $ECR_REPO:$IMAGE_TAG $REGISTRY/$ECR_REPO:$IMAGE_TAG
          docker tag $ECR_REPO:$IMAGE_TAG $REGISTRY/$ECR_REPO:${{ steps.ver.outputs.version }}
          docker tag $ECR_REPO:$IMAGE_TAG $REGISTRY/$ECR_REPO:latest

      - name: Push image
        env:
          REGISTRY: ${{ steps.ecr.outputs.registry }}
        run: |
          docker push $REGISTRY/$ECR_REPO:$IMAGE_TAG
          docker push $REGISTRY/$ECR_REPO:${{ steps.ver.outputs.version }}
          docker push $REGISTRY/$ECR_REPO:latest

      # ---------- GitOps: env-config Dev PR ----------
      # 포크 PR에선 시크릿이 주입되지 않으므로, 그 경우 이 블록은 skip
      - name: Check secrets available (skip on fork PR)
        id: secretcheck
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ] && [ "${{ github.event.pull_request.head.repo.fork }}" = "true" ]; then
            echo "skip=true" >> $GITHUB_OUTPUT
            echo "Fork PR: skipping overlay PR creation (no secrets)."
          else
            echo "skip=false" >> $GITHUB_OUTPUT
          fi

      - name: Guard PAT
        if: steps.secretcheck.outputs.skip == 'false'
        run: |
          test -n "${{ secrets.ENV_REPO_PAT }}" || (echo "ENV_REPO_PAT is empty"; exit 1)

      - name: Diagnose overlay access
        if: steps.secretcheck.outputs.skip == 'false'
        env:
          REPO: ${{ env.ENV_OVERLAY_REPO }}
        run: |
          git ls-remote https://x-access-token:${{ secrets.ENV_REPO_PAT }}@github.com/${REPO} HEAD

      - name: Checkout env overlay repo
        if: steps.secretcheck.outputs.skip == 'false'
        uses: actions/checkout@v4
        with:
          repository: ${{ env.ENV_OVERLAY_REPO }}
          token: ${{ secrets.ENV_REPO_PAT }}
          path: overlay

      - name: Update kustomize image tag (Dev)
        if: steps.secretcheck.outputs.skip == 'false'
        run: |
          set -eu
          file="overlay/${DEV_OVERLAY_PATH}"
          echo "Patching $file"
          sed -i -E "s#(newTag: ).*#\1${IMAGE_TAG}#g" "$file"
          grep -n "newTag:" "$file" || true

      - name: Create PR to env-config-dev
        if: steps.secretcheck.outputs.skip == 'false'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.ENV_REPO_PAT }}
          path: overlay
          base: main
          branch: chore/dev-bump-${{ github.sha }}
          title: "chore(dev): bump image to ${{ github.sha }} (also ${{ steps.ver.outputs.version }})"
          commit-message: "chore(dev): bump image to ${{ env.IMAGE_TAG }} (${{ steps.ver.outputs.version }})"
          body: |
            Update Dev image tag to `${{ github.sha }}`
            Additional tags: `${{ steps.ver.outputs.version }}`, `latest`
